const http = require('http');
const fs = require('fs');
const path = require('path');

// Configuration from environment
const configServerUrl = process.env.NEXT_PUBLIC_CONFIG_SERVER_URL || 'http://localhost:3009';
const publicKey = process.env.NEXT_PUBLIC_CONFIG_KEY || 'zone4food-public-key';
const env = process.env.NODE_ENV || 'developpement';
const serviceName = 'shop-ui';

console.log(`📡 [Shop-Build] Fetching build-time config for ${serviceName}/${env} from ${configServerUrl}...`);

const url = `${configServerUrl}/public/${serviceName}/${env === 'development' ? 'developpement' : env}`;

const req = http.get(url, {
    headers: {
        'x-public-key': publicKey
    }
}, (res) => {
    let data = '';
    res.on('data', (chunk) => { data += chunk; });
    res.on('end', () => {
        if (res.statusCode !== 200) {
            console.error(`❌ [Shop-Build] Failed to fetch config: ${res.statusCode} ${data}`);
            process.exit(0); // Exit gracefully in build context if server is not yet up (optional)
        }

        try {
            const config = JSON.parse(data);
            let envContent = '# AUTO-GENERATED BY fetch-config.js\n';

            for (const [key, value] of Object.entries(config)) {
                // Map keys to NEXT_PUBLIC if they don't have it
                const envKey = key.startsWith('NEXT_PUBLIC_') ? key : `NEXT_PUBLIC_${key}`;
                envContent += `${envKey}="${value}"\n`;
            }

            fs.writeFileSync(path.join(__dirname, '.env.local'), envContent);
            console.log('✅ [Shop-Build] .env.local generated successfully with remote config.');
        } catch (e) {
            console.error('❌ [Shop-Build] Error parsing config:', e.message);
        }
    });
});

req.on('error', (err) => {
    console.error('⚠️ [Shop-Build] Config server unreachable. Using local defaults.');
});
